### ISSUE TITLE
Replace resources

### ISSUE THREAD

**Issue by smutch** [mccoy-devs/mccoy#28]
We need to replace the resources with something more suitable for distribution.

**Comment by smutch** [comment]
This is also needed because the tree construction with the current dataset is numerically unstable and irreproducible for the purposes of testing (even when passing a fixed random seed to iqtree).

**Comment by Wytamma** [comment]
I’ll try to add this today and update the tests to match

**Comment by smutch** [comment]
> This is also needed because the tree construction with the current dataset is numerically unstable and irreproducible for the purposes of testing (even when passing a fixed random seed to iqtree).

This is no longer an issues after 3a03935, but we do still need to replace the data before release. :)

**Comment by smutch** [comment]
Closed by 159ec025ba80
